[build-system]
requires = [
    "setuptools",
    "setuptools-scm",
    "wheel",
]
build-backend="setuptools.build_meta"

[project]
name = "clip_bbox"
authors = [{name = "Grace Su", email = "grace.duansu@gmail.com"}]
description="Python library for detecting image objects with natural language text labels"
readme = "README.md"
version = "0.2.0"
requires-python = ">=3.7"

dependencies = ["torch==1.7.1", "torchvision", "ftfy", "regex"]

classifiers = [
    "Development Status :: 2 - Pre-Alpha",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
]


[project.license]
file = "LICENSE"

[project.urls]
repository = "https://github.com/graceduansu/clip_bbox"

[project.optional-dependencies]
develop = [
    "black>=22",
    "bump2version>=1.0.0",
    "check-manifest",
    "flake8>=3.7.8",
    "flake8-black>=0.2.1",
    "flake8-pyproject",
    "mypy",
    "pytest>=4.3.0",
    "pytest-cov>=2.6.1",
    "recommonmark",
    "sphinx",
    "sphinx_rtd_theme",
    "twine",
    "wheel",
]

[tool.black]
color = true
line-length = 120
target-version = ['py310']
skip-string-normalization = true
preview = true

[tool.check-manifest]
ignore = [
]

[tool.flake8]
ignore = ['E203', 'W503', 'E741']
max-line-length=120
per-file-ignores= [
    'clip_bbox/__init__.py:F401, F403',
    'clip_bbox/clip/__init__.py:F401, F403',
    'clip_bbox/tests/__init__.py:F401, F403'
]

[tool.isort]
line_length = 120
known_first_party = 'pydantic'
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
combine_as_imports = true

[tool.mypy]
python_version = '3.8'
# show_error_codes = true
# follow_imports = 'silent'
# strict_optional = true
# warn_redundant_casts = true
# warn_unused_ignores = true
# disallow_any_generics = true
# check_untyped_defs = true
# no_implicit_reexport = true
# warn_unused_configs = true
# disallow_subclassing_any = true
# disallow_incomplete_defs = true
# disallow_untyped_decorators = true
# disallow_untyped_calls = true

[tool.pytest.ini_options]
asyncio_mode = 'strict'
testpaths = 'clip_bbox/tests'
pythonpath = [
  ".", "clip_bbox"
]
